name: build-ios-app
on:
  push:
    branches:
      - 'master'
jobs:
  build:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v3
        with:
          node-version: 16
      - uses: actions/setup-java@v3
        with:
          distribution: 'zulu' # See 'Supported distributions' for available options
          java-version: '15'
      - uses: actions/setup-ruby@v1
        with:
          ruby-version: '2.6'
      - name: Install Node Modules
          run:npm ci  
      - name: Build and Deploy on UAT
        script: |
            cd android
            bundle install
            fastlane createAPK
            

        