name: build-ios-app
on:
  push:
    branches:
      - 'master'


permissions: read-all

jobs:
  build:
    runs-on: macos-latest
    steps:
      # - run : sudo chown -R $USER:$USER ${{ github.workspace }}
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v3
        with:
          node-version: 16
      - uses: actions/setup-java@v3
        with:
          distribution: 'zulu' # See 'Supported distributions' for available options
          java-version: '15'
      - uses: actions/setup-ruby@v1

      # - run: npm install
      #   name: Install Node Modules
      
      - run: echo ${{env.apikey}}
        name: Install Node Modules

      # - run: |
      #     cd android
      #     bundle install
      #     bundle exec fastlane createAPK
          
 
          